services:
  frontend:
    build:
      context: ./RubikCubeUI       
      dockerfile: Dockerfile-dev   
    container_name: rubik-cube-ui   
    ports:
      - "5173:5173"
    volumes:
      - ./RubikCubeUI:/app 
      - /app/node_modules  # Prevent host node_modules override
    environment:
      - API_BASE=http://localhost:8100/api/rubiksCube
